# Nombre de la aplicación
spring.application.name=ResiSmart Backend

# Puerto del servidor
server.port=${SERVER_PORT:8080}

# Perfil
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Actuator
management.endpoints.web.exposure.include=health,info

# ------------ Base de Datos (host -> contenedor en 55432) ------------
# (hazlo explícito para evitar que alguna ENV lo pise)
spring.datasource.url=jdbc:postgresql://localhost:5432/resismart
spring.datasource.username=postgres
spring.datasource.password=200232

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Seguridad (dev)
spring.security.user.name=admin
spring.security.user.password=1234
spring.security.user.roles=ADMIN

# (Temporal) para ver la URL efectiva de Hikari
# logging.level.com.zaxxer.hikari=DEBUG
