spring.application.name=ResiSmart Backend
server.port=8080
spring.profiles.active=dev

# --- Conexión a Postgres en Docker expuesto en 55432 ---
spring.datasource.url=jdbc:postgresql://localhost:55432/resismart
spring.datasource.username=postgres
spring.datasource.password=200232

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# (Opcional) seguridad dev
spring.security.user.name=admin
spring.security.user.password=1234
spring.security.user.roles=ADMIN
