spring.application.name=ResiSmart Backend

# Puerto configurable por variable de entorno SERVER_PORT (fallback 8080)
server.port=${SERVER_PORT:8080}

# Perfil por defecto (dev) ? también se puede activar con SPRING_PROFILES_ACTIVE
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Actuator básico (opcional para ver /actuator/health)
management.endpoints.web.exposure.include=health,info

spring.datasource.url=jdbc:postgresql://localhost:5432/resismart
spring.datasource.username=postgres
spring.datasource.password=200232
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=1234
spring.security.user.roles=ADMIN
